#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 31 15:40:13 2016

@author: demondrelivingston
"""


import json, requests

myToken='0e3018b1bd9124c6d7d1ec6be992af0b'
request = requests.post('http://challenge.code2040.org/api/prefix', json={'token':myToken})
arry=json.loads(request.text)
prefix=arry['prefix']
words=arry['array']
answer=[]
for x in words:
    if not x.startswith(prefix):
        answer.append(x)
request1=requests.post('http://challenge.code2040.org/api/prefix/validate',json={'token':myToken, 'array':answer})
print(request1.text)
